POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "json is usually translated to string form",
    "important": false
}

### doesnt work bc in mongo our id is much more complex, i tried 21 and could not parse 21 string into object id for some reason
GET http://localhost:3001/api/notes/215352636747 

###
GET http://localhost:3001/api/notes

###

PUT http://localhost:3001/api/notes/5ff722cf0e9a4e16f47330a8
Content-Type: application/json

{
    "content": "i am updating this note",
    "important": true
}